name: CI

"on":
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
  security-events: write

jobs:
  python:
    uses: mbologna/.github/.github/workflows/python-ci.yml@14e07c88dd4dfeec401cfc276db760334f670e84 # main
    with:
      python_version: "3.12"
      use_uv: false
      enable_codecov: true
    secrets: inherit

  docker:
    needs: python
    uses: mbologna/.github/.github/workflows/docker-ci.yml@14e07c88dd4dfeec401cfc276db760334f670e84 # main
    with:
      image_name: reddit-rss-fetcher
      push_to_dockerhub: false
      enable_grype: true
      enable_cosign: true
      enable_release_drafter: true
    secrets: inherit

  deploy:
    needs: [docker]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: mbologna/.github/.github/workflows/gcp-deploy.yml@14e07c88dd4dfeec401cfc276db760334f670e84 # main
    with:
      image_name: reddit-rss-fetcher
      ar_image: us-central1-docker.pkg.dev/reddit-rss-fetcher-cal/fetcher/app
      deploy_type: job
      deploy_name: reddit-rss-fetcher
      region: us-central1
    secrets: inherit

  deploy_server:
    needs: [docker]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: mbologna/.github/.github/workflows/gcp-deploy.yml@14e07c88dd4dfeec401cfc276db760334f670e84 # main
    with:
      image_name: reddit-rss-fetcher
      ar_image: us-central1-docker.pkg.dev/reddit-rss-fetcher-cal/fetcher/app
      deploy_type: service
      deploy_name: reddit-rss-server
      region: us-central1
    secrets: inherit
